### ISSUE TITLE
Add Validation to Vote Registration Screen

### ISSUE THREAD

**Issue by Beninja** [rndmorris/WU-CM333-EVoting#5]
In order to run our initial tests we will need to have some validation on the voter registration screen.

**Comment by Beninja** [comment]
Is this done?

**Comment by shannon594** [comment]
Yep!

**Comment by rndmorris** [comment]
Did you finish this, Shannon?  I don't remember _me_ finishing it.

**Comment by rndmorris** [comment]
_NOW_ it's done.
